name: Create Release .mix Files

permissions:
  contents: write

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-n-publish:
    name: Build and publish .mix files for release tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.x"
    - name: Install requirements
      run: >-
        python3 -m
        pip install -r
        scripts/requirements.txt
        --user
    - name: Build Urban .mix file
      run: >-
        python3 ./scripts/mix_handler.py
        create
        "./Development Files/YR/Urban"
        expandspawn13.mix
    - name: Build Temperate .mix file
      run: >-
        python3 ./scripts/mix_handler.py
        create
        "./Development Files/YR/Temperate"
        expandspawn14.mix
    - name: Build Snow .mix file
      run: >-
        python3 ./scripts/mix_handler.py
        create
        "./Development Files/YR/Snow"
        expandspawn15.mix
    - name: Build NewUrban .mix file
      run: >-
        python3 ./scripts/mix_handler.py
        create
        "./Development Files/YR/NewUrban"
        expandspawn16.mix
    - name: Build Lunar .mix file
      run: >-
        python3 ./scripts/mix_handler.py
        create
        "./Development Files/YR/Lunar"
        expandspawn17.mix
    - name: Build Desert .mix file
      run: >-
        python3 ./scripts/mix_handler.py
        create
        "./Development Files/YR/Desert"
        expandspawn18.mix
    - name: Save release files
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          expandspawn1*.mix
          Development Files/YR/*/*.ini
